use crate::components::traits::renderable::Renderable;

/// If a component has OnTick trait, this indicates that the component requires a tick that is
/// automatically and periodically generated by the program. Tick allows the component to update
/// itself without user input.
pub trait OnTick: Renderable {
    fn on_tick(&mut self);
}
